/**
 * Global tooltip. Any element with data-tip="<html>" gets a tooltip via event
 * delegation – no per-element listeners. Content is generated by our own
 * templates (escaped), never from user input.
 * The map uses show()/hide() directly for hover information.
 */
export class Tooltip {
  constructor(el) {
    this.el = el;
    this.current = null;
    this.manual = false;
    document.addEventListener('pointerover', (ev) => {
      if (ev.pointerType === 'touch') return;
      const target = ev.target.closest?.('[data-tip]');
      if (target === this.current) return;
      this.current = target;
      if (target) this.show(target.dataset.tip, ev.clientX, ev.clientY);
      else if (!this.manual) this.hide();
    });
    document.addEventListener('pointermove', (ev) => {
      if (this.current) this.position(ev.clientX, ev.clientY);
    });
    document.addEventListener('pointerdown', () => {
      if (this.current) this.hide();
    });
    document.addEventListener('focusin', (ev) => {
      const target = ev.target.closest?.('[data-tip]');
      if (target && target.matches(':focus-visible')) {
        const r = target.getBoundingClientRect();
        this.current = target;
        this.show(target.dataset.tip, r.left + r.width / 2, r.bottom);
      }
    });
    document.addEventListener('focusout', () => {
      if (this.current) this.hide();
    });
  }

  show(html, x, y) {
    this.el.innerHTML = html;
    this.el.hidden = false;
    this.position(x, y);
  }

  position(x, y) {
    const pad = 14;
    const r = this.el.getBoundingClientRect();
    let left = x + pad;
    let top = y + pad;
    if (left + r.width > window.innerWidth - 8) left = x - r.width - pad;
    if (top + r.height > window.innerHeight - 8) top = y - r.height - pad;
    this.el.style.transform = `translate(${Math.max(8, left)}px, ${Math.max(8, top)}px)`;
  }

  /** Manual mode (map hover). */
  showAt(html, x, y) {
    this.manual = true;
    this.show(html, x, y);
  }

  hide() {
    this.current = null;
    this.manual = false;
    this.el.hidden = true;
  }
}
